-- ============================================================================
-- SEED DATA: Reference data, sample customers, policies, interactions, claims
-- Run AFTER DCM deploy to populate tables with test data
-- ============================================================================

USE DATABASE INSURANCE_DB;
USE SCHEMA RAW;


-- RAW.CUSTOMERS
INSERT INTO INSURANCE_DB.RAW.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, ADDRESS, CITY, STATE_PROVINCE, PIN_CODE, CUSTOMER_SEGMENT, LIFETIME_VALUE_SCORE, ONBOARDING_DATE, KYC_STATUS, PREFERRED_CHANNEL) VALUES ('CUST001', 'Rajesh', 'Krishnamurthy', 'rajesh.k@techfirm.in', '+91-9876543210', '1975-03-15', '42 Tech Park Road, Manapakkam', 'Chennai', 'Tamil Nadu', '600089', 'HNW', 0.92, '2015-01-10', 'VERIFIED', 'CALL');
INSERT INTO INSURANCE_DB.RAW.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, ADDRESS, CITY, STATE_PROVINCE, PIN_CODE, CUSTOMER_SEGMENT, LIFETIME_VALUE_SCORE, ONBOARDING_DATE, KYC_STATUS, PREFERRED_CHANNEL) VALUES ('CUST002', 'Priya', 'Venkatesh', 'priya.v@startup.io', '+91-9876543211', '1988-07-22', '15 Innovation Drive, Manapakkam', 'Chennai', 'Tamil Nadu', '600089', 'SME', 0.65, '2019-06-01', 'VERIFIED', 'EMAIL');
INSERT INTO INSURANCE_DB.RAW.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, ADDRESS, CITY, STATE_PROVINCE, PIN_CODE, CUSTOMER_SEGMENT, LIFETIME_VALUE_SCORE, ONBOARDING_DATE, KYC_STATUS, PREFERRED_CHANNEL) VALUES ('CUST003', 'Arjun', 'Sundaram', 'arjun.s@gmail.com', '+91-9876543212', '1992-11-08', '78 Velachery Main Road', 'Chennai', 'Tamil Nadu', '600042', 'STANDARD', 0.35, '2022-03-15', 'VERIFIED', 'SMS');
INSERT INTO INSURANCE_DB.RAW.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, ADDRESS, CITY, STATE_PROVINCE, PIN_CODE, CUSTOMER_SEGMENT, LIFETIME_VALUE_SCORE, ONBOARDING_DATE, KYC_STATUS, PREFERRED_CHANNEL) VALUES ('CUST004', 'Meenakshi', 'Rajan', 'meena.r@manufacturing.co.in', '+91-9876543213', '1970-05-30', '101 Industrial Estate, Manapakkam', 'Chennai', 'Tamil Nadu', '600089', 'HNW', 0.88, '2012-09-01', 'VERIFIED', 'CALL');
INSERT INTO INSURANCE_DB.RAW.CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, ADDRESS, CITY, STATE_PROVINCE, PIN_CODE, CUSTOMER_SEGMENT, LIFETIME_VALUE_SCORE, ONBOARDING_DATE, KYC_STATUS, PREFERRED_CHANNEL) VALUES ('CUST005', 'Vikram', 'Patel', 'vikram.p@fakemail.com', '+91-9876543214', '1995-01-01', '99 Unknown Street', 'Chennai', 'Tamil Nadu', '600001', 'STANDARD', 0.15, '2024-11-01', 'VERIFIED', 'PORTAL');


-- RAW.POLICIES
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-AUTO-001', 'CUST001', 'AUTO', 'ACTIVE', '2024-01-01', '2025-12-31', '2025-12-31', 45000.0, 2500000.0, 25000.0, 'LOW', 'CHENNAI_MANAPAKKAM', 'PREFERRED');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-AUTO-003', 'CUST003', 'AUTO', 'ACTIVE', '2024-03-01', '2025-02-28', '2025-02-28', 12000.0, 500000.0, 10000.0, 'MEDIUM', 'CHENNAI_VELACHERY', 'STANDARD');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-AUTO-005', 'CUST005', 'AUTO', 'ACTIVE', '2024-11-01', '2025-10-31', '2025-10-31', 8000.0, 300000.0, 5000.0, 'HIGH', 'CHENNAI_GENERAL', 'STANDARD');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-PROP-001', 'CUST001', 'PROPERTY', 'ACTIVE', '2024-01-01', '2025-12-31', '2025-12-31', 95000.0, 50000000.0, 500000.0, 'LOW', 'CHENNAI_MANAPAKKAM', 'PREFERRED');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-PROP-002', 'CUST002', 'PROPERTY', 'ACTIVE', '2024-06-01', '2025-05-31', '2025-05-31', 25000.0, 5000000.0, 100000.0, 'MEDIUM', 'CHENNAI_MANAPAKKAM', 'STANDARD');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-PROP-004', 'CUST004', 'PROPERTY', 'ACTIVE', '2024-01-01', '2025-12-31', '2025-12-31', 120000.0, 100000000.0, 1000000.0, 'LOW', 'CHENNAI_MANAPAKKAM', 'PREFERRED');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-WC-001', 'CUST001', 'WORKERS_COMP', 'ACTIVE', '2024-01-01', '2025-12-31', '2025-12-31', 40000.0, 10000000.0, 50000.0, 'LOW', 'CHENNAI_MANAPAKKAM', 'PREFERRED');
INSERT INTO INSURANCE_DB.RAW.POLICIES (POLICY_ID, CUSTOMER_ID, LOB_TYPE, POLICY_STATUS, START_DATE, END_DATE, RENEWAL_DATE, PREMIUM_ANNUAL, COVERAGE_LIMIT, DEDUCTIBLE, UNDERWRITING_TIER, GEOGRAPHIC_ZONE, PROVIDER_NETWORK) VALUES ('POL-WC-004', 'CUST004', 'WORKERS_COMP', 'ACTIVE', '2024-01-01', '2025-12-31', '2025-12-31', 60000.0, 20000000.0, 100000.0, 'MEDIUM', 'CHENNAI_MANAPAKKAM', 'PREFERRED');


-- RAW.FRAUD_INDICATORS
INSERT INTO INSURANCE_DB.RAW.FRAUD_INDICATORS (INDICATOR_ID, PATTERN_TYPE, PATTERN_DESCRIPTION, EXAMPLE_NARRATIVE, LOB_TYPE, SEVERITY, CONFIRMED_CASES, LAST_SEEN_DATE) VALUES ('FRD-001', 'DISASTER_OPPORTUNISM', 'Claims submitted immediately after a publicized disaster event by customers with no geographic or temporal connection to the incident. Key signals: new policy (<6 months), no prior claims, vague location details, inflated amounts relative to coverage, urgency pressure language ("need money urgently", "personal emergency"). Often uses generic descriptions without specific details about the actual incident.', 'My car was damaged in the fire area. Everything destroyed. Need money urgently for personal emergency. Dont have photos. Car was somewhere near the incident.', 'AUTO', 'HIGH', 45, '2024-08-15');
INSERT INTO INSURANCE_DB.RAW.FRAUD_INDICATORS (INDICATOR_ID, PATTERN_TYPE, PATTERN_DESCRIPTION, EXAMPLE_NARRATIVE, LOB_TYPE, SEVERITY, CONFIRMED_CASES, LAST_SEEN_DATE) VALUES ('FRD-002', 'DUPLICATE_SUBMISSION', 'Same incident claimed multiple times across different policy numbers or slightly different descriptions. Key signals: same incident date, same customer, similar claim text, overlapping coverage. Note: legitimate multi-LOB claims from genuine disasters are NOT duplicates - they cover different assets under different policies.', 'Two claims for same vehicle damage submitted under different policy numbers with slightly altered descriptions.', 'AUTO', 'MEDIUM', 120, '2024-12-01');
INSERT INTO INSURANCE_DB.RAW.FRAUD_INDICATORS (INDICATOR_ID, PATTERN_TYPE, PATTERN_DESCRIPTION, EXAMPLE_NARRATIVE, LOB_TYPE, SEVERITY, CONFIRMED_CASES, LAST_SEEN_DATE) VALUES ('FRD-003', 'INFLATED_BILLING', 'Claim amounts significantly exceeding the actual value of the damaged asset or market rates for repairs. Key signals: claim amount > 80% of coverage limit on low-value asset, amount exceeds market value, unfamiliar provider, no supporting documentation from recognized providers.', 'Claiming Rs 2.8 lakhs damage on a 2018 Maruti Alto valued at Rs 3 lakhs. Amount is 93% of vehicle value for non-total-loss claim.', 'AUTO', 'HIGH', 89, '2024-11-20');
INSERT INTO INSURANCE_DB.RAW.FRAUD_INDICATORS (INDICATOR_ID, PATTERN_TYPE, PATTERN_DESCRIPTION, EXAMPLE_NARRATIVE, LOB_TYPE, SEVERITY, CONFIRMED_CASES, LAST_SEEN_DATE) VALUES ('FRD-004', 'STAGED_ACCIDENT', 'Accident details that dont match physical evidence or witness accounts. Common in auto claims. Key signals: inconsistent damage patterns, no independent witnesses, provider known for fraud, excessive treatment for minor injury.', 'Vehicle shows front-end damage but claim describes rear collision. No police report filed. Garage previously flagged.', 'AUTO', 'CRITICAL', 32, '2024-10-05');
INSERT INTO INSURANCE_DB.RAW.FRAUD_INDICATORS (INDICATOR_ID, PATTERN_TYPE, PATTERN_DESCRIPTION, EXAMPLE_NARRATIVE, LOB_TYPE, SEVERITY, CONFIRMED_CASES, LAST_SEEN_DATE) VALUES ('FRD-005', 'EMOTIONAL_MANIPULATION', 'Claim narratives using excessive emotional language, urgency, personal hardship stories to pressure fast approval without documentation. Key signals: urgency phrases, hardship narrative, resistance to documentation requests, threats.', 'Please process immediately, I am in dire need. My family depends on this. I cannot provide documents right now due to personal crisis. Just approve it.', 'AUTO', 'MEDIUM', 67, '2024-09-12');


-- RAW.INTERACTIONS
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-001', 'CUST001', 'CALL', '2025-01-15T15:30:00', 'Call transcript: Customer is extremely distressed. Speaking rapidly. "This is Rajesh Krishnamurthy, policy holder. There has been a massive fire at Manapakkam Tech Park. My entire office is destroyed. My cars are gone. Three of my employees are in hospital. I need someone from your company here NOW. This is a catastrophe. I have been a loyal customer for 10 years paying Rs 1.8 lakhs annual premium. I expect priority treatment. My staff are suffering. The fire department is still on scene. I will send all documents but I need immediate acknowledgment that my claims will be fast-tracked. This is not a normal situation."', 'INBOUND', 'CLAIM_EMERGENCY', 'ESCALATED', 'AGT-005', 420, NULL);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-002', 'CUST001', 'CALL', '2025-01-16T09:00:00', 'Call transcript: Follow-up call next day. Customer calmer but still stressed. "Good morning, this is Rajesh again regarding the Manapakkam fire claims. I have three claims submitted yesterday - auto, property, and workers comp. I need a single point of contact. I cannot be explaining the same disaster to three different departments. My employees need medical attention and the hospital is asking for payment guarantee. Can you assign a dedicated claims manager? Also, I noticed competitor XYZ Insurance is advertising faster claims settlement. I have been considering moving my portfolio if this is not handled properly."', 'INBOUND', 'CLAIM_FOLLOWUP', 'PENDING', 'AGT-005', 300, 4);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-003', 'CUST004', 'CALL', '2025-01-15T16:00:00', 'Call transcript: "This is Meenakshi Rajan from Chennai Manufacturing Corp. Our factory in Manapakkam Industrial Estate has been affected by the fire spreading from the tech park. Half our production floor is damaged and 12 workers are injured. We need emergency claims processing. Our policy numbers are POL-PROP-004 and POL-WC-004. The fire department report will be available tomorrow. We have CCTV footage. Please expedite."', 'INBOUND', 'CLAIM_EMERGENCY', 'ESCALATED', 'AGT-007', 280, NULL);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-004', 'CUST003', 'EMAIL', '2025-01-16T11:00:00', 'Subject: Claim for car damage - Manapakkam fire. Hi, I am writing to follow up on my claim CLM-003-AUTO submitted yesterday. My car was parked on the road near the tech park. The garage has given me a detailed estimate. When can I expect the surveyor to visit? I am managing with public transport for now. Thanks, Arjun.', 'INBOUND', 'CLAIM_FOLLOWUP', 'RESOLVED', 'AGT-003', 0, 7);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-005', 'CUST002', 'CHAT', '2025-01-17T14:00:00', 'Chat transcript: Customer: "Hi, any update on my property claim? Its been 2 days." Agent: "Your claim CLM-002-PROP is being processed. Surveyor scheduled for tomorrow." Customer: "OK thanks. We are operating from a co-working space currently. The team morale is low. We just raised Series A funding and this fire is very bad timing. Hope the settlement is quick." Agent: "We understand the urgency. Will prioritize."', 'INBOUND', 'CLAIM_STATUS', 'RESOLVED', 'AGT-002', 0, 6);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-006', 'CUST001', 'CALL', '2026-10-01T03:45:52.460000', 'Call transcript: Customer is visibly frustrated. "I have been waiting 3 weeks for my property claim settlement. Rs 3.2 crore claim and nobody can give me a timeline? My friend Suresh switched to HDFC Ergo last month and got his claim settled in 5 days. I am seriously considering moving all my policies. You people charge premium rates but give standard service. I want to speak with your manager right now."', 'INBOUND', 'CLAIM_FOLLOWUP', 'ESCALATED', 'AGT-003', 480, 2);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-007', 'CUST001', 'EMAIL', '2026-10-02T03:45:52.460000', 'Subject: Formal complaint - Unacceptable claim processing delay. Dear Sir/Madam, This is my third follow-up regarding claims CLM-001-PROP and CLM-001-AUTO. Despite being a loyal customer for over 8 years with annual premiums exceeding Rs 15 lakhs, I am treated like any walk-in customer. I have received a competitive quote from Bajaj Allianz that offers better coverage at 20% lower premium. Unless my claims are resolved within this week, I will be initiating the process to transfer all six of my policies. This is not a threat but a business decision. Regards, Rajesh Krishnamurthy.', 'INBOUND', 'COMPLAINT', 'PENDING', 'AGT-005', 0, 1);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-008', 'CUST001', 'CHAT', '2026-10-02T21:45:52.460000', 'Chat transcript: Customer: "I want to cancel my auto renewal for all policies. How do I do this?" Agent: "I understand your frustration Mr. Krishnamurthy. May I ask what prompted this?" Customer: "Your competitor offered me comprehensive cover for all 3 LOBs at Rs 12 lakhs vs the Rs 18 lakhs I pay you. And they guarantee 48-hour claim processing." Agent: "Let me connect you with our retention team who can review your portfolio." Customer: "Fine, but if they cannot match the offer, I am done."', 'INBOUND', 'CANCELLATION', 'ESCALATED', 'AGT-002', 320, 1);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-009', 'CUST002', 'CALL', '2026-09-30T03:45:52.460000', 'Call transcript: "Hi, this is Priya from Venkatesh Enterprises. The surveyor was supposed to visit our damaged property two days ago but nobody showed up. We have employees sitting idle because we cannot start repairs without the survey. Every day of delay costs us Rs 2 lakhs in lost productivity. When is someone actually coming?"', 'INBOUND', 'CLAIM_FOLLOWUP', 'PENDING', 'AGT-001', 300, 4);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-010', 'CUST002', 'CHAT', '2026-10-02T03:45:52.460000', 'Chat transcript: Customer: "Surveyor finally came yesterday. Report looks OK. When will I get the settlement?" Agent: "The surveyor report is being reviewed. Typically 5-7 business days." Customer: "OK that is acceptable. One more thing - we are expanding to a second office. Can someone call me about adding that to our property policy?" Agent: "I will have our business team reach out within 24 hours."', 'INBOUND', 'POLICY_INQUIRY', 'RESOLVED', 'AGT-004', 180, 7);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-011', 'CUST003', 'CALL', '2026-09-28T03:45:52.460000', 'Call transcript: "I received my renewal notice and the premium has gone up by 15%. That is too much. I checked online and Digit Insurance offers the same auto coverage for Rs 8000 less. Also ICICI Lombard has a zero-depreciation add-on at no extra cost. Why should I stay with you? I am a careful driver with zero claims in 3 years."', 'INBOUND', 'RENEWAL', 'PENDING', 'AGT-003', 420, 3);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-012', 'CUST003', 'EMAIL', '2026-10-01T03:45:52.460000', 'Subject: Premium comparison request. Hi, Can you please send me a detailed breakup of my auto policy premium? I want to compare with 3 other quotes I have received. Specifically I want to understand why comprehensive coverage is Rs 45000 when Digit offers it at Rs 37000. Also please confirm my NCB percentage. Thanks, Arjun.', 'INBOUND', 'BILLING', 'RESOLVED', 'AGT-005', 0, 4);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-013', 'CUST004', 'CALL', '2026-09-29T03:45:52.460000', 'Call transcript: "This is Meenakshi from Chennai Manufacturing Corp. We had a workplace injury last week and your claims team is asking for documents we already submitted twice. My HR team has spent 20 hours on paperwork instead of helping the injured worker. We pay premium for workers comp precisely so this process is smooth. I need this resolved today."', 'INBOUND', 'CLAIM_FOLLOWUP', 'ESCALATED', 'AGT-001', 540, 3);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-014', 'CUST004', 'CALL', '2026-10-02T03:45:52.460000', 'Call transcript: "Thank you for expediting the workers comp claim. The settlement came through yesterday and our employee is getting the treatment. However I want to discuss increasing our coverage limits - we are hiring 50 more factory workers next quarter and the current policy may not be adequate. Can we schedule a review?"', 'INBOUND', 'POLICY_INQUIRY', 'RESOLVED', 'AGT-003', 360, 8);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-015', 'CUST005', 'CALL', '2026-09-26T03:45:52.460000', 'Call transcript: Customer is extremely agitated. "This is absolutely ridiculous. You denied my claim saying the damage was pre-existing. My car was in perfect condition before the accident! I have the service records to prove it. Your investigator did not even look at my evidence. I am going to file a complaint with IRDAI. This is the worst insurance company I have ever dealt with."', 'INBOUND', 'CLAIM_DISPUTE', 'ESCALATED', 'AGT-002', 720, 1);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-016', 'CUST005', 'EMAIL', '2026-09-28T03:45:52.460000', 'Subject: IRDAI complaint notice. To whom it may concern, I am writing to inform you that I have filed a formal complaint with IRDAI regarding the unfair denial of my auto claim CLM-005-AUTO. I have also posted reviews on Google, MouthShut, and social media about my experience. I demand a senior manager call me within 24 hours to resolve this or I will take legal action. Vikram Patel.', 'INBOUND', 'COMPLAINT', 'PENDING', 'AGT-005', 0, 1);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-017', 'CUST005', 'CALL', '2026-10-01T03:45:52.460000', 'Call transcript: "Your manager called but offered nothing useful. Just excuses. I have already started the process with New India Assurance. They are offering me a fresh policy with immediate effect. I want to cancel my current policy and get a refund for the remaining period. I am done with your company permanently."', 'INBOUND', 'CANCELLATION', 'PENDING', 'AGT-001', 300, 1);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-018', 'CUST004', 'CHAT', '2026-10-02T15:45:52.460000', 'Chat transcript: Customer: "Just wanted to say thank you for the quick resolution on our workers comp claim. Very professional handling." Agent: "Thank you Ms. Rajan! We are always here to help. Is there anything else?" Customer: "Yes, can you send me the premium quote for the expanded coverage we discussed? We want to finalize by next week."', 'INBOUND', 'FEEDBACK', 'RESOLVED', 'AGT-004', 120, 9);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-019', 'CUST002', 'CALL', '2026-10-03T00:45:52.460000', 'Call transcript: "Hi, this is Priya. Good news - the property repairs are going well. I wanted to check if we can add cyber insurance to our SME package? We had a close call with a phishing attack last month and it scared us. Also can we discuss directors and officers liability? We are planning an IPO next year."', 'INBOUND', 'POLICY_INQUIRY', 'RESOLVED', 'AGT-003', 240, 8);
INSERT INTO INSURANCE_DB.RAW.INTERACTIONS (INTERACTION_ID, CUSTOMER_ID, CHANNEL, INTERACTION_DATE, TRANSCRIPT_TEXT, DIRECTION, TOPIC, RESOLUTION_STATUS, AGENT_ID, DURATION_SECONDS, NPS_SCORE) VALUES ('INT-020', 'CUST003', 'CALL', '2026-10-03T02:45:52.460000', 'Call transcript: "Hi, I spoke with your retention team yesterday. They offered me a 10% loyalty discount and added roadside assistance free for one year. That brings the premium close to what Digit quoted. I have decided to renew. Please process the renewal with the discount applied. Thanks for working with me on this."', 'INBOUND', 'RENEWAL', 'RESOLVED', 'AGT-002', 180, 7);


-- RAW.UNDERWRITING_GUIDELINES
INSERT INTO INSURANCE_DB.RAW.UNDERWRITING_GUIDELINES (GUIDELINE_ID, LOB_TYPE, SECTION_NAME, CONTENT, RISK_LEVEL, REGULATORY_REFERENCE, EFFECTIVE_DATE, STATUS) VALUES ('UG-001', 'AUTO', 'Vehicle Age and Condition', 'Vehicles older than 10 years require physical inspection before coverage. Depreciation applies at 10% per year after first 3 years. Total coverage cannot exceed IDV (Insured Declared Value). High-performance vehicles (>200HP) require additional premium of 15%. Electric vehicles get 5% discount.', 'ALL', 'IRDAI-Motor-2023', '2023-04-01', 'CURRENT');
INSERT INTO INSURANCE_DB.RAW.UNDERWRITING_GUIDELINES (GUIDELINE_ID, LOB_TYPE, SECTION_NAME, CONTENT, RISK_LEVEL, REGULATORY_REFERENCE, EFFECTIVE_DATE, STATUS) VALUES ('UG-002', 'PROPERTY', 'Commercial Property Fire Coverage', 'Fire coverage for commercial properties must include fire brigade charges, debris removal, and architects fees (up to 5% of claim). Electrical fire caused by faulty wiring - covered. Arson by owner - excluded. Sum insured must reflect current replacement value, not market value. Annual escalation of 8% recommended for commercial.', 'ALL', 'IRDAI-Fire-2023', '2023-04-01', 'CURRENT');
INSERT INTO INSURANCE_DB.RAW.UNDERWRITING_GUIDELINES (GUIDELINE_ID, LOB_TYPE, SECTION_NAME, CONTENT, RISK_LEVEL, REGULATORY_REFERENCE, EFFECTIVE_DATE, STATUS) VALUES ('UG-003', 'WORKERS_COMP', 'Workplace Injury Classification', 'Injuries classified as: Minor (first aid only, no leave), Moderate (medical attention, <7 days leave), Severe (hospitalization, >7 days), Critical (life-threatening, ICU). Compensation: Minor=medical only, Moderate=medical+50% wages, Severe=medical+75% wages+disability, Critical=medical+100% wages+disability+family support.', 'ALL', 'IRDAI-WC-2023', '2023-04-01', 'CURRENT');
INSERT INTO INSURANCE_DB.RAW.UNDERWRITING_GUIDELINES (GUIDELINE_ID, LOB_TYPE, SECTION_NAME, CONTENT, RISK_LEVEL, REGULATORY_REFERENCE, EFFECTIVE_DATE, STATUS) VALUES ('UG-004', 'PROPERTY', 'High-Value Property Risk Assessment', 'Properties with sum insured >Rs 5 crore require: (1) Fire safety audit, (2) Sprinkler system verification, (3) Electrical safety certificate <6 months old, (4) Building stability certificate. Risk tier: LOW if all 4 present, MEDIUM if 2-3, HIGH if 0-1. Premium multiplier: LOW=1.0x, MEDIUM=1.3x, HIGH=1.8x.', 'HIGH', 'IRDAI-Property-2023', '2023-04-01', 'CURRENT');
INSERT INTO INSURANCE_DB.RAW.UNDERWRITING_GUIDELINES (GUIDELINE_ID, LOB_TYPE, SECTION_NAME, CONTENT, RISK_LEVEL, REGULATORY_REFERENCE, EFFECTIVE_DATE, STATUS) VALUES ('UG-005', 'AUTO', 'Fleet Insurance Underwriting', 'Fleet of 3+ vehicles: bundle discount 10%. Fleet of 10+: 15%. All vehicles must be registered to same owner/company. Mix of personal and commercial use disqualifies fleet discount. GPS tracking installed: additional 5% discount. No-claim bonus applies per vehicle, not fleet-wide.', 'LOW', 'IRDAI-Motor-2023', '2023-04-01', 'CURRENT');


-- RAW.RETENTION_PLAYBOOKS
INSERT INTO INSURANCE_DB.RAW.RETENTION_PLAYBOOKS (PLAYBOOK_ID, CUSTOMER_SEGMENT, ROOT_CAUSE, PLAYBOOK_NAME, CONTENT, SUCCESS_RATE, APPLICABLE_LOB) VALUES ('PB-001', 'HNW', 'poor_claims_experience', 'VIP Claims Recovery Playbook', 'For HNW customers showing dissatisfaction after a claims experience: (1) Assign dedicated senior claims manager within 4 hours, (2) Provide direct mobile number for updates, (3) Fast-track remaining claims to 48-hour resolution, (4) Schedule executive callback from branch head within 24 hours, (5) Offer complimentary coverage enhancement for next renewal period, (6) Document service recovery in CRM for renewal team.', 0.78, 'ALL');
INSERT INTO INSURANCE_DB.RAW.RETENTION_PLAYBOOKS (PLAYBOOK_ID, CUSTOMER_SEGMENT, ROOT_CAUSE, PLAYBOOK_NAME, CONTENT, SUCCESS_RATE, APPLICABLE_LOB) VALUES ('PB-002', 'STANDARD', 'price_sensitivity', 'Standard Retention - Price Sensitive', 'For standard customers citing pricing concerns: (1) Review current premium vs market benchmark, (2) Offer 10% loyalty discount if tenure >2 years, (3) Suggest deductible increase for premium reduction, (4) Bundle offer: add second LOB for 15% total discount, (5) Highlight no-claim bonus accrued. Do NOT offer more than 15% total discount - refer to manager if needed.', 0.55, 'ALL');
INSERT INTO INSURANCE_DB.RAW.RETENTION_PLAYBOOKS (PLAYBOOK_ID, CUSTOMER_SEGMENT, ROOT_CAUSE, PLAYBOOK_NAME, CONTENT, SUCCESS_RATE, APPLICABLE_LOB) VALUES ('PB-003', 'HNW', 'competitor_offer', 'HNW Counter-Competitive Playbook', 'When HNW customer mentions competitor: (1) Never disparage competitor, (2) Emphasize relationship value and claims track record, (3) Offer dedicated relationship manager (if not already assigned), (4) Match or beat competitor premium if within 5% (pre-approved), (5) Offer premium lock for 3 years, (6) Highlight multi-LOB integration advantage competitors cannot match.', 0.72, 'ALL');
INSERT INTO INSURANCE_DB.RAW.RETENTION_PLAYBOOKS (PLAYBOOK_ID, CUSTOMER_SEGMENT, ROOT_CAUSE, PLAYBOOK_NAME, CONTENT, SUCCESS_RATE, APPLICABLE_LOB) VALUES ('PB-004', 'SME', 'poor_claims_experience', 'SME Claims Recovery', 'For SME customers with bad claims experience: (1) Acknowledge the experience explicitly, (2) Assign business insurance specialist, (3) Expedite any open claims, (4) Offer business continuity consultation (free), (5) 5% renewal discount as goodwill, (6) Quarterly check-in calls scheduled.', 0.62, 'ALL');


-- RAW.CLAIMS_LANDING
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('98cf21e7-1310-4f98-8510-75fcbfc2f68b', 'POL-AUTO-850', 'CUST850', 'SFSF', '2026-10-02', 100000.0, 'AUTO', 'DQ_FAILED', 'See description');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('CLM-001-AUTO', 'POL-AUTO-001', 'CUST001', 'Massive fire at Manapakkam Tech Park on 15th Jan 2025. My BMW X5 (TN01AB1234) and Mercedes E-Class (TN01CD5678) were parked in the basement parking of Block B. Both vehicles are completely gutted - total loss. The fire started in the electrical room on the ground floor around 2 PM and spread rapidly. I was in a meeting on the 3rd floor when the alarm went off. By the time fire services arrived the basement was an inferno. I have the fire department incident report and CCTV footage showing the timeline. Please process urgently as I need transport for my team.', '2025-01-15', 4500000.0, 'AUTO', 'APPROVED', 'Block B Basement Parking, Tech Park, Manapakkam, Chennai');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('CLM-001-PROP', 'POL-PROP-001', 'CUST001', 'Our entire office on the 3rd floor of Block B, Manapakkam Tech Park has been destroyed in the fire on January 15th. All server rooms, workstations (150+ machines), furniture, and documents are gone. The structural engineer says the floor is compromised and cannot be reoccupied. We have the fire department report, structural assessment, and our asset inventory. The preliminary estimate from our contractor Landmark Constructions is Rs 3.2 crore for rebuild and equipment replacement. We need emergency workspace arrangements for 250 employees immediately.', '2025-01-15', 32000000.0, 'PROPERTY', 'APPROVED', '3rd Floor, Block B, Tech Park, Manapakkam, Chennai');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('CLM-001-WC', 'POL-WC-001', 'CUST001', 'Three of my employees were hospitalized due to the Manapakkam Tech Park fire on January 15th. Suresh Kumar (EMP-101) suffered second-degree burns on arms and face while helping evacuate colleagues. Lakshmi Devi (EMP-205) inhaled heavy smoke and is in ICU with respiratory distress. Ravi Shankar (EMP-089) fell during evacuation and fractured his right leg. All three are at Apollo Hospital, Guindy. Medical bills are mounting - Suresh alone is at Rs 8 lakhs already. I need immediate claim processing and direct hospital settlement if possible.', '2025-01-15', 2500000.0, 'WORKERS_COMP', 'APPROVED', 'Block B, Tech Park, Manapakkam + Apollo Hospital, Guindy');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('CLM-002-PROP', 'POL-PROP-002', 'CUST002', 'Our startup office at 15 Innovation Drive was affected by the Manapakkam fire. While our building did not catch fire directly, the adjacent Block B collapse caused debris to crash through our windows and roof. We have water damage from the fire department hoses. Our server rack (8 servers), 20 MacBooks, and all office furniture are damaged. Contractor estimate for repairs is Rs 18 lakhs. We had just signed a Series A and cannot afford this setback. Photos and contractor report attached.', '2025-01-15', 1800000.0, 'PROPERTY', 'APPROVED', '15 Innovation Drive, adjacent to Block B, Manapakkam');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('CLM-003-AUTO', 'POL-AUTO-003', 'CUST003', 'My Hyundai i20 was parked on the street near Manapakkam Tech Park when the fire happened on Jan 15. Falling debris hit the car and the heat cracked the windshield and melted the rear bumper. Garage estimate is Rs 1.5 lakhs for repairs. I have photos and the garage assessment from Sri Balaji Motors.', '2025-01-15', 150000.0, 'AUTO', 'APPROVED', 'Street parking, Manapakkam Road, near Tech Park');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('CLM-005-AUTO', 'POL-AUTO-005', 'CUST005', 'My car was damaged badly in the Manapakkam fire area. Everything is destroyed. I need Rs 2.8 lakhs for the damage. The car was parked somewhere near the tech park. I dont remember exactly where. It happened around the same time as the big fire. I dont have photos because my phone was also damaged. The garage says it will cost a lot. Please process quickly I need the money urgently for personal emergency.', '2025-01-15', 280000.0, 'AUTO', 'APPROVED', 'Near Manapakkam Tech Park area');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('c7b98ce5-b249-4021-b624-9b979ec1925f', NULL, 'CUST150', 'Suffered injury while climbing stairs', '2026-10-02', 50000.0, 'WORKERS_COMP', 'DQ_FAILED', 'Workplace');
INSERT INTO INSURANCE_DB.RAW.CLAIMS_LANDING (CLAIM_ID, POLICY_ID, CUSTOMER_ID, CLAIM_TEXT, INCIDENT_DATE, CLAIMED_AMOUNT, LOB_TYPE, CLAIM_STATUS, INCIDENT_LOCATION) VALUES ('da7df61f-f3a7-4812-ba26-82166496fb4f', NULL, 'CUST003', 'Suffered injury while climbing stairs', '2026-10-02', 50000.0, 'WORKERS_COMP', 'DENIED', 'Workplace');

-- RAW.PROVIDERS
INSERT INTO INSURANCE_DB.RAW.PROVIDERS (PROVIDER_ID, PROVIDER_NAME, PROVIDER_TYPE, LOB_TYPE, NETWORK_STATUS, RISK_FLAG, AVG_BILLING_AMOUNT, TOTAL_CLAIMS_SERVED, FRAUD_FLAG_COUNT, LOCATION_CITY, LOCATION_STATE, LICENSE_NUMBER) VALUES ('PROV-001', 'Apollo Hospital Guindy', 'HOSPITAL', 'WORKERS_COMP', 'IN_NETWORK', FALSE, 350000, 1200, 0, 'Chennai', 'Tamil Nadu', 'MH-TN-2345');
INSERT INTO INSURANCE_DB.RAW.PROVIDERS (PROVIDER_ID, PROVIDER_NAME, PROVIDER_TYPE, LOB_TYPE, NETWORK_STATUS, RISK_FLAG, AVG_BILLING_AMOUNT, TOTAL_CLAIMS_SERVED, FRAUD_FLAG_COUNT, LOCATION_CITY, LOCATION_STATE, LICENSE_NUMBER) VALUES ('PROV-002', 'Sri Balaji Motors', 'GARAGE', 'AUTO', 'IN_NETWORK', FALSE, 85000, 800, 0, 'Chennai', 'Tamil Nadu', 'GA-TN-5678');
INSERT INTO INSURANCE_DB.RAW.PROVIDERS (PROVIDER_ID, PROVIDER_NAME, PROVIDER_TYPE, LOB_TYPE, NETWORK_STATUS, RISK_FLAG, AVG_BILLING_AMOUNT, TOTAL_CLAIMS_SERVED, FRAUD_FLAG_COUNT, LOCATION_CITY, LOCATION_STATE, LICENSE_NUMBER) VALUES ('PROV-003', 'Landmark Constructions', 'CONTRACTOR', 'PROPERTY', 'IN_NETWORK', FALSE, 5000000, 150, 0, 'Chennai', 'Tamil Nadu', 'CN-TN-9012');
INSERT INTO INSURANCE_DB.RAW.PROVIDERS (PROVIDER_ID, PROVIDER_NAME, PROVIDER_TYPE, LOB_TYPE, NETWORK_STATUS, RISK_FLAG, AVG_BILLING_AMOUNT, TOTAL_CLAIMS_SERVED, FRAUD_FLAG_COUNT, LOCATION_CITY, LOCATION_STATE, LICENSE_NUMBER) VALUES ('PROV-004', 'QuickFix Garage', 'GARAGE', 'AUTO', 'OUT_NETWORK', TRUE, 250000, 50, 8, 'Chennai', 'Tamil Nadu', 'GA-TN-0000');
INSERT INTO INSURANCE_DB.RAW.PROVIDERS (PROVIDER_ID, PROVIDER_NAME, PROVIDER_TYPE, LOB_TYPE, NETWORK_STATUS, RISK_FLAG, AVG_BILLING_AMOUNT, TOTAL_CLAIMS_SERVED, FRAUD_FLAG_COUNT, LOCATION_CITY, LOCATION_STATE, LICENSE_NUMBER) VALUES ('PROV-005', 'Shady Repairs Unlimited', 'GARAGE', 'AUTO', 'OUT_NETWORK', TRUE, 400000, 20, 15, 'Chennai', 'Tamil Nadu', 'GA-TN-FAKE');

-- RAW.PAYMENTS
INSERT INTO INSURANCE_DB.RAW.PAYMENTS (PAYMENT_ID, POLICY_ID, CUSTOMER_ID, PAYMENT_DATE, DUE_DATE, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, DAYS_DELAYED) VALUES ('PAY-001-01', 'POL-AUTO-001', 'CUST001', '2024-01-05', '2024-01-10', 45000, 'PAID', 'AUTO_DEBIT', 0);
INSERT INTO INSURANCE_DB.RAW.PAYMENTS (PAYMENT_ID, POLICY_ID, CUSTOMER_ID, PAYMENT_DATE, DUE_DATE, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, DAYS_DELAYED) VALUES ('PAY-001-02', 'POL-PROP-001', 'CUST001', '2024-01-05', '2024-01-10', 95000, 'PAID', 'NEFT', 0);
INSERT INTO INSURANCE_DB.RAW.PAYMENTS (PAYMENT_ID, POLICY_ID, CUSTOMER_ID, PAYMENT_DATE, DUE_DATE, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, DAYS_DELAYED) VALUES ('PAY-001-03', 'POL-WC-001', 'CUST001', '2024-01-05', '2024-01-10', 40000, 'PAID', 'NEFT', 0);
INSERT INTO INSURANCE_DB.RAW.PAYMENTS (PAYMENT_ID, POLICY_ID, CUSTOMER_ID, PAYMENT_DATE, DUE_DATE, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, DAYS_DELAYED) VALUES ('PAY-003-01', 'POL-AUTO-003', 'CUST003', '2024-03-20', '2024-03-10', 12000, 'PAID', 'UPI', 10);
INSERT INTO INSURANCE_DB.RAW.PAYMENTS (PAYMENT_ID, POLICY_ID, CUSTOMER_ID, PAYMENT_DATE, DUE_DATE, AMOUNT, PAYMENT_STATUS, PAYMENT_METHOD, DAYS_DELAYED) VALUES ('PAY-005-01', 'POL-AUTO-005', 'CUST005', '2024-11-05', '2024-11-05', 8000, 'PAID', 'CARD', 0);

-- RAW.ACTUARIAL_TABLES
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-001', 'AUTO', 'LOW', 'CHENNAI_GENERAL', 0.035, 1.0, 1.1, 1.0, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-002', 'AUTO', 'MEDIUM', 'CHENNAI_GENERAL', 0.035, 1.3, 1.1, 1.2, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-003', 'AUTO', 'HIGH', 'CHENNAI_GENERAL', 0.035, 1.8, 1.1, 1.5, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-004', 'PROPERTY', 'LOW', 'CHENNAI_MANAPAKKAM', 0.0025, 1.0, 1.3, 1.0, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-005', 'PROPERTY', 'MEDIUM', 'CHENNAI_MANAPAKKAM', 0.0025, 1.4, 1.3, 1.3, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-006', 'PROPERTY', 'HIGH', 'CHENNAI_MANAPAKKAM', 0.0025, 2.0, 1.3, 1.6, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-007', 'WORKERS_COMP', 'LOW', 'CHENNAI_MANAPAKKAM', 0.02, 1.0, 1.0, 1.0, '2024-01-01', '2025-12-31');
INSERT INTO INSURANCE_DB.RAW.ACTUARIAL_TABLES (TABLE_ID, LOB_TYPE, RISK_TIER, GEOGRAPHIC_ZONE, BASE_RATE, RISK_MULTIPLIER, GEOGRAPHIC_FACTOR, CLAIMS_HISTORY_FACTOR, EFFECTIVE_DATE, EXPIRY_DATE) VALUES ('ACT-008', 'WORKERS_COMP', 'MEDIUM', 'CHENNAI_MANAPAKKAM', 0.02, 1.3, 1.0, 1.2, '2024-01-01', '2025-12-31');

