-- ============================================================================
-- ACCESS CONTROL: Roles, role hierarchy, and grants
-- ============================================================================

-- Role definitions
DEFINE ROLE INSURANCE_APP_ROLE
    COMMENT = 'Service role for agent pipeline execution';

DEFINE ROLE INSURANCE_ADJUSTER_ROLE
    COMMENT = 'Claims adjusters - view decisions and Customer 360';

DEFINE ROLE INSURANCE_UNDERWRITER_ROLE
    COMMENT = 'Underwriters - view/action underwriting decisions';

DEFINE ROLE INSURANCE_RETENTION_ROLE
    COMMENT = 'Retention analysts - view churn alerts and NBA';

DEFINE ROLE INSURANCE_ADMIN_ROLE
    COMMENT = 'Admin - full database management';

-- Role hierarchy
GRANT ROLE INSURANCE_APP_ROLE TO ROLE INSURANCE_ADMIN_ROLE;
GRANT ROLE INSURANCE_ADJUSTER_ROLE TO ROLE INSURANCE_ADMIN_ROLE;
GRANT ROLE INSURANCE_UNDERWRITER_ROLE TO ROLE INSURANCE_ADMIN_ROLE;
GRANT ROLE INSURANCE_RETENTION_ROLE TO ROLE INSURANCE_ADMIN_ROLE;
GRANT ROLE INSURANCE_ADMIN_ROLE TO ROLE SYSADMIN;

-- App role: full CRUD on all schemas
GRANT USAGE ON DATABASE INSURANCE_DB TO ROLE INSURANCE_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DB.RAW TO ROLE INSURANCE_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DB.PROCESSED TO ROLE INSURANCE_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DB.RESULTS TO ROLE INSURANCE_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DB.VECTORS TO ROLE INSURANCE_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DB.FEATURES TO ROLE INSURANCE_APP_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DB.STAGES TO ROLE INSURANCE_APP_ROLE;

-- Adjuster role: read RESULTS + PROCESSED
GRANT USAGE ON DATABASE INSURANCE_DB TO ROLE INSURANCE_ADJUSTER_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DB.RESULTS TO ROLE INSURANCE_ADJUSTER_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DB.PROCESSED TO ROLE INSURANCE_ADJUSTER_ROLE;

-- Underwriter role: read RESULTS + RAW
GRANT USAGE ON DATABASE INSURANCE_DB TO ROLE INSURANCE_UNDERWRITER_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DB.RESULTS TO ROLE INSURANCE_UNDERWRITER_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DB.RAW TO ROLE INSURANCE_UNDERWRITER_ROLE;

-- Retention role: read PROCESSED
GRANT USAGE ON DATABASE INSURANCE_DB TO ROLE INSURANCE_RETENTION_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DB.PROCESSED TO ROLE INSURANCE_RETENTION_ROLE;
